### ISSUE TITLE
よくあるトラブルとその対処法リストを作りたい

### ISSUE THREAD

**Issue by MofuMofu2** [MofuMofu2/TB4-Elastic-Stack-6#4]
もうほんと血管が切れそうなので、よく遭遇するトラブルとその対処法を書いておきたい
そんで「はーあやってらんねっす」とか言いながら本見て修正するみたいにしたい

もふちゃんがんばるからみんなトラブル例ください

**Comment by MofuMofu2** [comment]
これは間に合わないきがするな

**Comment by micci184** [comment]
このエラーメッセージ出た時は、ここを確かめろよ！的なのは、少し書けるかも
